services:
  navegantus-postgres:
    image: postgres:16
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    command: -p ${DATABASE_PORT}